export type GeneratedGameAssets = {
  slug: string;
  icon: string;
  headerImage: string;
  screenshots: string[];
  syncedAt: string;
};

// This file is generated by scripts/sync-playstore-assets.mjs.
export const generatedGameAssets: GeneratedGameAssets[] = [
  {
    "slug": "skincare-asmr-spa",
    "icon": "/images/games/skincare-asmr-spa/store/icon.png",
    "headerImage": "/images/games/skincare-asmr-spa/store/screenshot-1.jpg",
    "screenshots": [
      "/images/games/skincare-asmr-spa/store/screenshot-1.jpg",
      "/images/games/skincare-asmr-spa/store/screenshot-2.jpg",
      "/images/games/skincare-asmr-spa/store/screenshot-3.jpg",
      "/images/games/skincare-asmr-spa/store/screenshot-4.jpg"
    ],
    "syncedAt": "2026-04-13T07:45:37.263Z"
  },
  {
    "slug": "shuriken-slice",
    "icon": "/images/games/shuriken-slice/store/icon.jpg",
    "headerImage": "/images/games/shuriken-slice/store/screenshot-1.jpg",
    "screenshots": [
      "/images/games/shuriken-slice/store/screenshot-1.jpg",
      "/images/games/shuriken-slice/store/screenshot-2.jpg",
      "/images/games/shuriken-slice/store/screenshot-3.jpg",
      "/images/games/shuriken-slice/store/screenshot-4.jpg"
    ],
    "syncedAt": "2026-04-13T07:45:38.211Z"
  },
  {
    "slug": "scary-survival-house",
    "icon": "/images/games/scary-survival-house/store/icon.png",
    "headerImage": "/images/games/scary-survival-house/store/screenshot-1.jpg",
    "screenshots": [
      "/images/games/scary-survival-house/store/screenshot-1.jpg",
      "/images/games/scary-survival-house/store/screenshot-2.jpg",
      "/images/games/scary-survival-house/store/screenshot-3.jpg",
      "/images/games/scary-survival-house/store/screenshot-4.jpg"
    ],
    "syncedAt": "2026-04-13T07:45:38.957Z"
  },
  {
    "slug": "fire-shooting-battle-royale",
    "icon": "/images/games/fire-shooting-battle-royale/store/icon.png",
    "headerImage": "/images/games/fire-shooting-battle-royale/store/screenshot-1.jpg",
    "screenshots": [
      "/images/games/fire-shooting-battle-royale/store/screenshot-1.jpg",
      "/images/games/fire-shooting-battle-royale/store/screenshot-2.jpg",
      "/images/games/fire-shooting-battle-royale/store/screenshot-3.jpg",
      "/images/games/fire-shooting-battle-royale/store/screenshot-4.jpg"
    ],
    "syncedAt": "2026-04-13T07:45:40.090Z"
  },
  {
    "slug": "harvest-crop-farm-town",
    "icon": "/images/games/harvest-crop-farm-town/store/icon.png",
    "headerImage": "/images/games/harvest-crop-farm-town/store/screenshot-1.jpg",
    "screenshots": [
      "/images/games/harvest-crop-farm-town/store/screenshot-1.jpg",
      "/images/games/harvest-crop-farm-town/store/screenshot-2.jpg",
      "/images/games/harvest-crop-farm-town/store/screenshot-3.jpg",
      "/images/games/harvest-crop-farm-town/store/screenshot-4.jpg"
    ],
    "syncedAt": "2026-04-13T07:45:41.094Z"
  }
];
